include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_await_in_return: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_interpolations: true
    use_build_context_synchronously: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
